### ISSUE TITLE
Thumbnail missing in options

### ISSUE THREAD

**Issue by onakahetta** [soundchaser128/stash-compilation-maker#10]
Hi,
Thank  you for sharing the great tool, it gets me nice compilations with ease. but i encountered a problem with dispaying thumbnails in 'select marker/scene' pages. 
![image](https://user-images.githubusercontent.com/9284456/234463064-d2ed7d35-a92b-46e0-a1a0-2affc383e8c1.png)
stash-compilation-maker doesn't give any error messages and I'm wondering how to solve this issue. I appreciate your help.

**Comment by soundchaser128** [comment]
Have you generated scene covers inside stash? I think those are necessary for that to work.

**Comment by onakahetta** [comment]
Hi, thank you for looking into this.
![console](https://user-images.githubusercontent.com/9284456/235308185-ea9627fe-9c54-4e7f-acff-f14274441ec5.jpg)

**Comment by soundchaser128** [comment]
Oh, I think you might have a space at the start of your API key (the API key parameter in your URL starts with a +, which would indicate that). I just tried it myself and that does seem to cause the issue on my machine as well. In the console of the server application you can see the location of the configuration file at startup ("trying to load config file from ..."). If you open that file in a text editor, check the value at the `apiKey` key and delete the space if it's there. Then restart the server and try again.

**Comment by onakahetta** [comment]
thamk you, it worked!

**Comment by soundchaser128** [comment]
Nice, glad to hear it.
