### ISSUE TITLE
Toggle for AND vs OR logic

### ISSUE THREAD

**Issue by iampabber** [soundchaser128/stash-compilation-maker#7]
Currently, if I create a Tag compilation with two Tags selected, all Markers with either Tag are chosen.

I would like to have a toggle which would allow me to select only Markers with both Tags, instead of markers with either tag.

**Comment by soundchaser128** [comment]
Ah, yeah, that makes sense.

**Comment by soundchaser128** [comment]
Released in 0.5.0: https://github.com/soundchaser128/stash-compilation-maker/releases/tag/v0.5.0

**Comment by iampabber** [comment]
TY
